import { useCallback, useEffect, useRef, useState } from 'react'
import type { Plate } from '../data/plates.generated'

export type Slide = {
  src: string
  /** Gradients that continue the image's own edge colours into the bars
      left empty by `object-contain`. Generated by scripts/generate-plates.mjs. */
  plate?: Plate
}

type ImageSliderProps = {
  slides: Slide[]
  alt: string
  interval?: number
  className?: string
}

const prefersReducedMotion = () =>
  typeof window !== 'undefined' &&
  window.matchMedia('(prefers-reduced-motion: reduce)').matches

export function ImageSlider({
  slides,
  alt,
  interval = 3000,
  className = '',
}: ImageSliderProps) {
  const [index, setIndex] = useState(0)
  const [active, setActive] = useState(true)
  const frameRef = useRef<HTMLDivElement | null>(null)

  // The outgoing plate is held opaque beneath the incoming one. Fading both
  // against the frame would let the base colour bleed through at the midpoint,
  // which lifts the bars on dark slides.
  const prevRef = useRef(index)
  useEffect(() => {
    prevRef.current = index
  }, [index])
  const prev = prevRef.current

  const go = useCallback(
    (next: number) => setIndex(((next % slides.length) + slides.length) % slides.length),
    [slides.length],
  )

  // Only run the timer while the slider is on screen and the tab is visible.
  useEffect(() => {
    const node = frameRef.current
    if (!node) return

    let visible = document.visibilityState !== 'hidden'
    let onScreen = true

    const sync = () => setActive(visible && onScreen)

    const observer = new IntersectionObserver(
      ([entry]) => {
        onScreen = entry.isIntersecting
        sync()
      },
      { threshold: 0.15 },
    )
    observer.observe(node)

    const onVisibility = () => {
      visible = document.visibilityState !== 'hidden'
      sync()
    }
    document.addEventListener('visibilitychange', onVisibility)

    return () => {
      observer.disconnect()
      document.removeEventListener('visibilitychange', onVisibility)
    }
  }, [])

  useEffect(() => {
    if (!active || slides.length < 2 || prefersReducedMotion()) return

    const id = window.setTimeout(() => go(index + 1), interval)
    return () => window.clearTimeout(id)
  }, [active, go, index, interval, slides.length])

  return (
    <div
      ref={frameRef}
      className={`group relative isolate overflow-hidden ${className}`}
      role="group"
      aria-roledescription="carousel"
      aria-label={alt}
    >
      <div className="relative aspect-[5/4] w-full bg-white">
        {/* Backdrops crossfade on the same clock as the images, so the bars
            never show the previous slide's colours. Kept outside the zoom
            wrapper — the bars should stay put while the photo scales. */}
        {slides.map((slide, i) => (
          <div
            key={slide.src}
            aria-hidden
            className={`absolute inset-0 transition-opacity duration-1000 ease-linear ${
              i === index || i === prev ? 'opacity-100' : 'opacity-0'
            }`}
            style={{
              zIndex: i === index ? 1 : 0,
              ...(slide.plate && {
                backgroundImage: slide.plate.image,
                backgroundSize: slide.plate.size,
                backgroundPosition: slide.plate.position,
                backgroundRepeat: 'no-repeat',
              }),
            }}
          />
        ))}

        {/* One transform on the whole stack — scaling each image separately
            forces the compositor to redraw every slide on hover. */}
        <div className="slider-zoom absolute inset-0 z-10">
          {slides.map((slide, i) => (
            <img
              key={slide.src}
              src={slide.src}
              alt={i === index ? alt : ''}
              aria-hidden={i !== index}
              loading={i === 0 ? 'eager' : 'lazy'}
              decoding="async"
              className={`absolute inset-0 h-full w-full object-contain transition-opacity duration-1000 ease-linear ${
                i === index ? 'opacity-100' : 'opacity-0'
              }`}
            />
          ))}
        </div>
      </div>

      {/* Dots sit in their own pill: the plate is white but the artwork
          behind them is not, so they need a carrier of their own. */}
      {slides.length > 1 && (
        <div className="absolute inset-x-0 bottom-0 z-20 flex justify-center p-4">
          <div className="flex items-center gap-2 rounded-full bg-black/55 px-3 py-2 backdrop-blur-sm">
            {slides.map((slide, i) => (
              <button
                key={slide.src}
                type="button"
                onClick={() => go(i)}
                aria-label={`${alt} — ${i + 1} / ${slides.length}`}
                aria-current={i === index}
                className={`h-1.5 rounded-full transition-all duration-500 ${
                  i === index
                    ? 'w-6 bg-prestige'
                    : 'w-1.5 bg-white/55 hover:bg-white'
                }`}
              />
            ))}
          </div>
        </div>
      )}
    </div>
  )
}
