/**
 * Samples the edge colours of every slider image and emits the CSS gradients
 * used as each slide's backdrop.
 *
 * The slider shows images with `object-contain`, so a portrait shot in a 5:4
 * frame leaves bars down the left and right, and a landscape shot leaves them
 * across the top and bottom. Rather than one flat colour behind everything,
 * each bar continues the colours along the edge it touches: the plate is built
 * from two gradients, one per bar, each sampled in vertical (or horizontal)
 * segments so it follows the image's own gradient instead of flattening it.
 *
 * Run after adding or replacing slider images:  npm run plates
 */
import sharp from 'sharp'
import { writeFileSync } from 'fs'

/** Colour stops per bar. Enough to follow a gradient, few enough to stay legible. */
const SEGMENTS = 6

// `frame` is the aspect the slider renders that set at — it decides which pair
// of bars `object-contain` leaves empty, so it must match the ImageSlider call.
const SETS = [
  { dir: 'Packages', count: 29, frame: 5 / 4 },
  { dir: 'Collection', count: 18, frame: 5 / 4 },
  { dir: 'Vynil', count: 2, frame: 4 / 3 },
  { dir: 'Napkins', count: 14, frame: 4 / 3 },
]

const hex = (r, g, b) =>
  '#' + [r, g, b].map((v) => Math.round(v).toString(16).padStart(2, '0')).join('')

const median = (values) => {
  const sorted = [...values].sort((a, b) => a - b)
  return sorted[Math.floor(sorted.length / 2)]
}

async function readPixels(file) {
  const { data, info } = await sharp(file)
    .raw()
    .toBuffer({ resolveWithObject: true })
  const { width, height, channels } = info
  return {
    width,
    height,
    at(x, y) {
      const o = (y * width + x) * channels
      return [data[o], data[o + 1], data[o + 2]]
    },
  }
}

/**
 * Median colour of a rectangular patch. Median rather than mean so a single
 * dark pixel bleeding in from the subject cannot drag the whole stop.
 */
function patch(img, x0, x1, y0, y1) {
  const pixels = []
  const stepX = Math.max(1, Math.round((x1 - x0) / 24))
  const stepY = Math.max(1, Math.round((y1 - y0) / 24))
  for (let y = y0; y < y1; y += stepY)
    for (let x = x0; x < x1; x += stepX) pixels.push(img.at(x, y))
  return [0, 1, 2].map((c) => median(pixels.map((p) => p[c])))
}

/** Builds a gradient string by walking one edge in SEGMENTS steps. */
function edgeGradient(img, edge) {
  const { width, height } = img
  const bandX = Math.max(2, Math.round(width * 0.02))
  const bandY = Math.max(2, Math.round(height * 0.02))
  const stops = []

  for (let s = 0; s < SEGMENTS; s++) {
    const from = s / SEGMENTS
    const to = (s + 1) / SEGMENTS
    let colour
    if (edge === 'left' || edge === 'right') {
      const y0 = Math.floor(height * from)
      const y1 = Math.max(y0 + 1, Math.floor(height * to))
      colour =
        edge === 'left'
          ? patch(img, 0, bandX, y0, y1)
          : patch(img, width - bandX, width, y0, y1)
    } else {
      const x0 = Math.floor(width * from)
      const x1 = Math.max(x0 + 1, Math.floor(width * to))
      colour =
        edge === 'top'
          ? patch(img, x0, x1, 0, bandY)
          : patch(img, x0, x1, height - bandY, height)
    }
    // Place each stop at its segment midpoint and let CSS interpolate between.
    const at = Math.round(((from + to) / 2) * 100)
    stops.push(`${hex(...colour)} ${at}%`)
  }

  // Vertical bars read top-to-bottom; horizontal bars read left-to-right.
  const angle = edge === 'left' || edge === 'right' ? '180deg' : '90deg'
  return `linear-gradient(${angle}, ${stops.join(', ')})`
}

async function plateFor(file, frame) {
  const img = await readPixels(file)
  const bars = img.width / img.height > frame ? 'horizontal' : 'vertical'

  if (bars === 'vertical') {
    // Portrait in a landscape frame: bars sit left and right, full height.
    return {
      image: `${edgeGradient(img, 'left')}, ${edgeGradient(img, 'right')}`,
      size: '50% 100%, 50% 100%',
      position: 'left center, right center',
    }
  }
  // Landscape in a taller frame: bars sit above and below, full width.
  return {
    image: `${edgeGradient(img, 'top')}, ${edgeGradient(img, 'bottom')}`,
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  }
}

const entries = []
for (const { dir, count, frame } of SETS) {
  for (let n = 1; n <= count; n++) {
    const key = `${dir}/${n}.webp`
    entries.push([key, await plateFor(`src/assets/${key}`, frame)])
    process.stdout.write(`  ${key}\n`)
  }
}

const body = entries
  .map(
    ([key, p]) =>
      `  '${key}': {\n` +
      `    image:\n      '${p.image}',\n` +
      `    size: '${p.size}',\n` +
      `    position: '${p.position}',\n` +
      `  },`,
  )
  .join('\n')

const out = `// Generated by scripts/generate-plates.mjs — do not edit by hand.
// Regenerate with: npm run plates

export type Plate = {
  /** One gradient per bar, in background-image order. */
  image: string
  size: string
  position: string
}

export const plates: Record<string, Plate> = {
${body}
}
`

writeFileSync('src/data/plates.generated.ts', out, 'utf8')
console.log(`\nWrote src/data/plates.generated.ts (${entries.length} plates)`)
