// Generated by scripts/generate-plates.mjs — do not edit by hand.
// Regenerate with: npm run plates

export type Plate = {
  /** One gradient per bar, in background-image order. */
  image: string
  size: string
  position: string
}

export const plates: Record<string, Plate> = {
  'Packages/1.webp': {
    image:
      'linear-gradient(180deg, #e5e8f2 8%, #e8edf8 25%, #eaeffb 42%, #eaeffb 58%, #eff3ff 75%, #eef4ff 92%), linear-gradient(180deg, #dee4eb 8%, #e6e9f3 25%, #e9ecf6 42%, #eaeffb 58%, #eff1fe 75%, #eff3ff 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/2.webp': {
    image:
      'linear-gradient(180deg, #d9e0ea 8%, #dfe4f0 25%, #e2e7f3 42%, #e6eaf6 58%, #eaeffb 75%, #e7eefb 92%), linear-gradient(180deg, #d5dae4 8%, #dce1eb 25%, #e1e4ef 42%, #e5e7f4 58%, #ebf0fc 75%, #eaeefb 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/3.webp': {
    image:
      'linear-gradient(180deg, #dfe7ef 8%, #e5ecf7 25%, #e7eefa 42%, #e7ecf8 58%, #eef6ff 75%, #eef6ff 92%), linear-gradient(180deg, #d9e1ea 8%, #e3e8f2 25%, #e6ecf6 42%, #e9ecf8 58%, #f0f4ff 75%, #f0f5ff 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/4.webp': {
    image:
      'linear-gradient(180deg, #d7dde7 8%, #dbe2ed 25%, #dfe4f0 42%, #e1e5f1 58%, #e6ebf9 75%, #e4e9f5 92%), linear-gradient(180deg, #d3d9e3 8%, #dadfe8 25%, #dde2ec 42%, #e3e6f1 58%, #e8edfa 75%, #e6e8f5 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/5.webp': {
    image:
      'linear-gradient(180deg, #e1e9f3 8%, #e6ebf7 25%, #eaeffb 42%, #eef5ff 58%, #eef5ff 75%, #ecf3fe 92%), linear-gradient(180deg, #e2e7f1 8%, #e6ebf6 25%, #ebf0fc 42%, #eff1fe 58%, #f0f5ff 75%, #ecf1fd 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/6.webp': {
    image:
      'linear-gradient(180deg, #e1e7f1 8%, #e6ecf7 25%, #e9eefa 42%, #e8ecf8 58%, #eef4ff 75%, #eef5ff 92%), linear-gradient(180deg, #dfe4ee 8%, #e6eaf4 25%, #e9edf8 42%, #eaedf8 58%, #f0f3ff 75%, #f0f5ff 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/7.webp': {
    image:
      'linear-gradient(180deg, #e4e7f2 8%, #e6ebf7 25%, #e6e8f5 42%, #ebf0fc 58%, #edf3fe 75%, #edf3fe 92%), linear-gradient(180deg, #dce2eb 8%, #e5e7f2 25%, #e7e9f4 42%, #eef0fb 58%, #f0f3ff 75%, #edf2fe 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/8.webp': {
    image:
      'linear-gradient(180deg, #bac5d2 8%, #c5cedb 25%, #ccd5e4 42%, #ced6e5 58%, #e1e9fb 75%, #dde7f7 92%), linear-gradient(180deg, #a8b0b9 8%, #bbc2cf 25%, #cbd2e0 42%, #d1d8e6 58%, #e5e9fa 75%, #e1e8f8 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/9.webp': {
    image:
      'linear-gradient(180deg, #dde6f6 8%, #e2ebfa 25%, #e0e8fa 42%, #e4ebfd 58%, #e9f0ff 75%, #e9f0ff 92%), linear-gradient(180deg, #d2dbe8 8%, #d9e1ef 25%, #dde4f1 42%, #e7eaf8 58%, #eaecfc 75%, #e9ebfa 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/10.webp': {
    image:
      'linear-gradient(180deg, #d9e0ee 8%, #e1e6f3 25%, #e5e8f8 42%, #e5e7f6 58%, #edf0fe 75%, #eef0ff 92%), linear-gradient(180deg, #d4d8e6 8%, #dee0ef 25%, #e1e4f2 42%, #e3e6f3 58%, #eef0fb 75%, #eef0fd 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/11.webp': {
    image:
      'linear-gradient(180deg, #dee5f2 8%, #e5ebf9 25%, #e8effd 42%, #e6edfa 58%, #ecf3fe 75%, #ecf3fe 92%), linear-gradient(180deg, #d7dee8 8%, #e2e5f0 25%, #e6e8f5 42%, #e6e8f5 58%, #eef0fd 75%, #eff1fe 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/12.webp': {
    image:
      'linear-gradient(180deg, #c7cce1 8%, #d1d8ec 25%, #dae0f4 42%, #d8def1 58%, #e0e5f9 75%, #e1e6fa 92%), linear-gradient(180deg, #c5c9dc 8%, #d1d6ea 25%, #d9ddf1 42%, #d6dcee 58%, #e3e5f9 75%, #e3e5f9 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/13.webp': {
    image:
      'linear-gradient(180deg, #dfe1f2 8%, #e8eafb 25%, #eef0ff 42%, #f0f3ff 58%, #f0f3ff 75%, #eceefd 92%), linear-gradient(180deg, #deddea 8%, #e8e5f4 25%, #eceaf8 42%, #f0eefc 58%, #efecfb 75%, #e8e6f2 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/14.webp': {
    image:
      'linear-gradient(180deg, #e5e7f8 8%, #eaeeff 25%, #eff1ff 42%, #f0f3ff 58%, #eff2ff 75%, #eaecfc 92%), linear-gradient(180deg, #dedeee 8%, #e3e2f2 25%, #e8e6f6 42%, #e8e7f7 58%, #e7e5f4 75%, #e1e0ee 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/15.webp': {
    image:
      'linear-gradient(90deg, #dedeee 8%, #e6e6f6 25%, #e8e8f8 42%, #eae9f9 58%, #e7e7f7 75%, #e3e2f2 92%), linear-gradient(90deg, #dfe4f6 8%, #e6eafd 25%, #eaefff 42%, #edf0ff 58%, #eaeefe 75%, #e3e6f6 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Packages/16.webp': {
    image:
      'linear-gradient(180deg, #f6f6f6 8%, #f7f8f8 25%, #f6f7f7 42%, #efefef 58%, #efefef 75%, #f6f6f6 92%), linear-gradient(180deg, #f7f7f7 8%, #f8f8f8 25%, #f9f9f9 42%, #f9f9f9 58%, #f6f6f6 75%, #f8f8f8 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Collection/1.webp': {
    image:
      'linear-gradient(180deg, #f8f4e8 8%, #d8d4cb 25%, #ddd5c2 42%, #ded5c1 58%, #e2dc88 75%, #775d45 92%), linear-gradient(180deg, #c995ba 8%, #776e87 25%, #4c4e4d 42%, #3d3f43 58%, #2f3238 75%, #413c39 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Collection/2.webp': {
    image:
      'linear-gradient(180deg, #403b2f 8%, #342426 25%, #2d1825 42%, #402530 58%, #3d242f 75%, #18120f 92%), linear-gradient(180deg, #aba599 8%, #8f7148 25%, #c29357 42%, #584833 58%, #a9a2af 75%, #c7b7b2 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Collection/3.webp': {
    image:
      'linear-gradient(180deg, #cbd1d6 8%, #c2b398 25%, #caba9e 42%, #bcad90 58%, #54524b 75%, #664c2e 92%), linear-gradient(180deg, #ccd5de 8%, #c0b399 25%, #c9ba9c 42%, #ccbda0 58%, #c8ba9c 75%, #baaa8a 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Collection/4.webp': {
    image:
      'linear-gradient(90deg, #908a7b 8%, #b9b19f 25%, #b5b1a0 42%, #69655c 58%, #aea997 75%, #a8a08d 92%), linear-gradient(90deg, #74716b 8%, #6e6c6a 25%, #65615e 42%, #5f5c58 58%, #544f4b 75%, #57554f 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Collection/5.webp': {
    image:
      'linear-gradient(90deg, #836925 8%, #a1957e 25%, #b8af9b 42%, #c3bdb4 58%, #b2aba0 75%, #a49b94 92%), linear-gradient(90deg, #a08531 8%, #c1bba2 25%, #cfcbb7 42%, #d4d1c0 58%, #d2d0c4 75%, #cac9bc 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Collection/6.webp': {
    image:
      'linear-gradient(180deg, #e6d462 8%, #e5d362 25%, #e3d05f 42%, #dfcd5c 58%, #ddcb5a 75%, #dac855 92%), linear-gradient(180deg, #dac65a 8%, #4f5253 25%, #424448 42%, #312a22 58%, #ccb850 75%, #d3c054 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Collection/7.webp': {
    image:
      'linear-gradient(90deg, #030306 8%, #030308 25%, #050308 42%, #090609 58%, #090607 75%, #020204 92%), linear-gradient(90deg, #070507 8%, #0c090c 25%, #0f0a0b 42%, #140e09 58%, #050306 75%, #020204 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Collection/8.webp': {
    image:
      'linear-gradient(90deg, #bca081 8%, #766755 25%, #5d5043 42%, #665949 58%, #637f46 75%, #5f6b41 92%), linear-gradient(90deg, #84a15e 8%, #879f65 25%, #d8cdcb 42%, #718b5b 58%, #aa9b8c 75%, #ac9b8a 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Collection/9.webp': {
    image:
      'linear-gradient(90deg, #aca29c 8%, #8e8981 25%, #726c65 42%, #4c453f 58%, #342e26 75%, #2d2922 92%), linear-gradient(90deg, #cdc9c5 8%, #cdc9c5 25%, #c6c3bf 42%, #b8b3ae 58%, #a59f97 75%, #857e74 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Collection/10.webp': {
    image:
      'linear-gradient(90deg, #ffffff 8%, #ffffff 25%, #8d8889 42%, #847e78 58%, #4b4745 75%, #44403b 92%), linear-gradient(90deg, #8c9096 8%, #8c939c 25%, #858f97 42%, #7c848e 58%, #71757c 75%, #000000 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Collection/11.webp': {
    image:
      'linear-gradient(90deg, #6194c9 8%, #6194c9 25%, #6796ca 42%, #6b9ccb 58%, #73a3cf 75%, #7ea9d3 92%), linear-gradient(90deg, #bab2ac 8%, #b7b1aa 25%, #b6b0a9 42%, #b5afa8 58%, #9e9791 75%, #11161d 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Collection/12.webp': {
    image:
      'linear-gradient(180deg, #fbdfa8 8%, #493723 25%, #24190e 42%, #2d2016 58%, #34251b 75%, #6e5c42 92%), linear-gradient(180deg, #80705d 8%, #7e6143 25%, #765f42 42%, #57442e 58%, #947a5b 75%, #feeaba 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
}
