// Generated by scripts/generate-plates.mjs — do not edit by hand.
// Regenerate with: npm run plates

export type Plate = {
  /** One gradient per bar, in background-image order. */
  image: string
  size: string
  position: string
}

export const plates: Record<string, Plate> = {
  'Packages/1.webp': {
    image:
      'linear-gradient(180deg, #e5e8f2 8%, #e8edf8 25%, #eaeffb 42%, #eaeffb 58%, #eff3ff 75%, #eef4ff 92%), linear-gradient(180deg, #dee4eb 8%, #e6e9f3 25%, #e9ecf6 42%, #eaeffb 58%, #eff1fe 75%, #eff3ff 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/2.webp': {
    image:
      'linear-gradient(180deg, #d9e0ea 8%, #dfe4f0 25%, #e2e7f3 42%, #e6eaf6 58%, #eaeffb 75%, #e7eefb 92%), linear-gradient(180deg, #d5dae4 8%, #dce1eb 25%, #e1e4ef 42%, #e5e7f4 58%, #ebf0fc 75%, #eaeefb 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/3.webp': {
    image:
      'linear-gradient(180deg, #dfe7ef 8%, #e5ecf7 25%, #e7eefa 42%, #e7ecf8 58%, #eef6ff 75%, #eef6ff 92%), linear-gradient(180deg, #d9e1ea 8%, #e3e8f2 25%, #e6ecf6 42%, #e9ecf8 58%, #f0f4ff 75%, #f0f5ff 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/4.webp': {
    image:
      'linear-gradient(180deg, #d7dde7 8%, #dbe2ed 25%, #dfe4f0 42%, #e1e5f1 58%, #e6ebf9 75%, #e4e9f5 92%), linear-gradient(180deg, #d3d9e3 8%, #dadfe8 25%, #dde2ec 42%, #e3e6f1 58%, #e8edfa 75%, #e6e8f5 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/5.webp': {
    image:
      'linear-gradient(180deg, #e1e9f3 8%, #e6ebf7 25%, #eaeffb 42%, #eef5ff 58%, #eef5ff 75%, #ecf3fe 92%), linear-gradient(180deg, #e2e7f1 8%, #e6ebf6 25%, #ebf0fc 42%, #eff1fe 58%, #f0f5ff 75%, #ecf1fd 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/6.webp': {
    image:
      'linear-gradient(180deg, #e1e7f1 8%, #e6ecf7 25%, #e9eefa 42%, #e8ecf8 58%, #eef4ff 75%, #eef5ff 92%), linear-gradient(180deg, #dfe4ee 8%, #e6eaf4 25%, #e9edf8 42%, #eaedf8 58%, #f0f3ff 75%, #f0f5ff 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/7.webp': {
    image:
      'linear-gradient(180deg, #e4e7f2 8%, #e6ebf7 25%, #e6e8f5 42%, #ebf0fc 58%, #edf3fe 75%, #edf3fe 92%), linear-gradient(180deg, #dce2eb 8%, #e5e7f2 25%, #e7e9f4 42%, #eef0fb 58%, #f0f3ff 75%, #edf2fe 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/8.webp': {
    image:
      'linear-gradient(180deg, #bac5d2 8%, #c5cedb 25%, #ccd5e4 42%, #ced6e5 58%, #e1e9fb 75%, #dde7f7 92%), linear-gradient(180deg, #a8b0b9 8%, #bbc2cf 25%, #cbd2e0 42%, #d1d8e6 58%, #e5e9fa 75%, #e1e8f8 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/9.webp': {
    image:
      'linear-gradient(180deg, #dde6f6 8%, #e2ebfa 25%, #e0e8fa 42%, #e4ebfd 58%, #e9f0ff 75%, #e9f0ff 92%), linear-gradient(180deg, #d2dbe8 8%, #d9e1ef 25%, #dde4f1 42%, #e7eaf8 58%, #eaecfc 75%, #e9ebfa 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/10.webp': {
    image:
      'linear-gradient(180deg, #d9e0ee 8%, #e1e6f3 25%, #e5e8f8 42%, #e5e7f6 58%, #edf0fe 75%, #eef0ff 92%), linear-gradient(180deg, #d4d8e6 8%, #dee0ef 25%, #e1e4f2 42%, #e3e6f3 58%, #eef0fb 75%, #eef0fd 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/11.webp': {
    image:
      'linear-gradient(180deg, #dee5f2 8%, #e5ebf9 25%, #e8effd 42%, #e6edfa 58%, #ecf3fe 75%, #ecf3fe 92%), linear-gradient(180deg, #d7dee8 8%, #e2e5f0 25%, #e6e8f5 42%, #e6e8f5 58%, #eef0fd 75%, #eff1fe 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/12.webp': {
    image:
      'linear-gradient(180deg, #c7cce1 8%, #d1d8ec 25%, #dae0f4 42%, #d8def1 58%, #e0e5f9 75%, #e1e6fa 92%), linear-gradient(180deg, #c5c9dc 8%, #d1d6ea 25%, #d9ddf1 42%, #d6dcee 58%, #e3e5f9 75%, #e3e5f9 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/13.webp': {
    image:
      'linear-gradient(180deg, #dfe1f2 8%, #e8eafb 25%, #eef0ff 42%, #f0f3ff 58%, #f0f3ff 75%, #eceefd 92%), linear-gradient(180deg, #deddea 8%, #e8e5f4 25%, #eceaf8 42%, #f0eefc 58%, #efecfb 75%, #e8e6f2 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/14.webp': {
    image:
      'linear-gradient(180deg, #e5e7f8 8%, #eaeeff 25%, #eff1ff 42%, #f0f3ff 58%, #eff2ff 75%, #eaecfc 92%), linear-gradient(180deg, #dedeee 8%, #e3e2f2 25%, #e8e6f6 42%, #e8e7f7 58%, #e7e5f4 75%, #e1e0ee 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/15.webp': {
    image:
      'linear-gradient(90deg, #dedeee 8%, #e6e6f6 25%, #e8e8f8 42%, #eae9f9 58%, #e7e7f7 75%, #e3e2f2 92%), linear-gradient(90deg, #dfe4f6 8%, #e6eafd 25%, #eaefff 42%, #edf0ff 58%, #eaeefe 75%, #e3e6f6 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Packages/16.webp': {
    image:
      'linear-gradient(180deg, #f6f6f6 8%, #f7f8f8 25%, #f6f7f7 42%, #efefef 58%, #efefef 75%, #f6f6f6 92%), linear-gradient(180deg, #f7f7f7 8%, #f8f8f8 25%, #f9f9f9 42%, #f9f9f9 58%, #f6f6f6 75%, #f8f8f8 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/17.webp': {
    image:
      'linear-gradient(90deg, #c9d5e5 8%, #cad5e4 25%, #cbd4e1 42%, #c8cfdc 58%, #c6cbd7 75%, #bcc3ce 92%), linear-gradient(90deg, #d6dde9 8%, #dbe0ec 25%, #d8dee9 42%, #dadfe8 58%, #d6dbe5 75%, #d5dbe4 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Packages/18.webp': {
    image:
      'linear-gradient(180deg, #010101 8%, #000000 25%, #010101 42%, #000000 58%, #010101 75%, #000000 92%), linear-gradient(180deg, #020202 8%, #010101 25%, #020202 42%, #010101 58%, #000000 75%, #000000 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/19.webp': {
    image:
      'linear-gradient(180deg, #999fa1 8%, #a5adaf 25%, #acb1b3 42%, #b2b6b9 58%, #bac1bf 75%, #c6cbc9 92%), linear-gradient(180deg, #9ca1a0 8%, #a7acab 25%, #abb0af 42%, #b5bab9 58%, #bac1bf 75%, #c0c7c5 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/20.webp': {
    image:
      'linear-gradient(180deg, #141413 8%, #0f0f0f 25%, #080808 42%, #030303 58%, #151513 75%, #242422 92%), linear-gradient(180deg, #151514 8%, #10100f 25%, #0a0a0a 42%, #030303 58%, #161714 75%, #2d2e2b 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/21.webp': {
    image:
      'linear-gradient(180deg, #908c89 8%, #d0ccc3 25%, #d1cec8 42%, #c8c5bc 58%, #afa89f 75%, #a09a90 92%), linear-gradient(180deg, #645d54 8%, #6f6a69 25%, #7b8084 42%, #383938 58%, #6f685d 75%, #7b746b 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/22.webp': {
    image:
      'linear-gradient(180deg, #161616 8%, #101010 25%, #070707 42%, #0e0e0e 58%, #1e1f1c 75%, #2c2b29 92%), linear-gradient(180deg, #151515 8%, #101010 25%, #080808 42%, #0e0e0e 58%, #282724 75%, #34322e 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/23.webp': {
    image:
      'linear-gradient(180deg, #c6c3a1 8%, #989489 25%, #8e9091 42%, #cdd4dc 58%, #a4a8ad 75%, #b8bdbd 92%), linear-gradient(180deg, #c6ccba 8%, #b4bab0 25%, #bab4b1 42%, #dad2d0 58%, #d0d3d5 75%, #b6b8b9 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/24.webp': {
    image:
      'linear-gradient(180deg, #e2e7e5 8%, #e1e6e3 25%, #dcdfde 42%, #d9dddc 58%, #d4d9d7 75%, #d4d7d7 92%), linear-gradient(180deg, #dfe4e0 8%, #dfe4df 25%, #dce0de 42%, #dadddc 58%, #dadddc 75%, #d8dddb 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/25.webp': {
    image:
      'linear-gradient(180deg, #151515 8%, #101010 25%, #0a0a0a 42%, #1a1a1a 58%, #1c1c1c 75%, #1f1f1f 92%), linear-gradient(180deg, #141414 8%, #111111 25%, #0a0a0a 42%, #181818 58%, #212121 75%, #262626 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/26.webp': {
    image:
      'linear-gradient(180deg, #fdfdfd 8%, #fdfdfd 25%, #fdfdfd 42%, #fdfdfd 58%, #fdfdfd 75%, #fdfdfd 92%), linear-gradient(180deg, #fdfdfd 8%, #fdfdfd 25%, #fdfdfd 42%, #fdfdfd 58%, #fdfdfd 75%, #fdfdfd 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/27.webp': {
    image:
      'linear-gradient(180deg, #d7dbdb 8%, #d8dddb 25%, #d1d4d5 42%, #b7bcbc 58%, #d0d4d3 75%, #d8dadb 92%), linear-gradient(180deg, #d2d6d8 8%, #ccd0d3 25%, #caced0 42%, #b4bcbd 58%, #c3cbcc 75%, #cacfd1 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/28.webp': {
    image:
      'linear-gradient(180deg, #ced0cf 8%, #d0d4d4 25%, #babbb8 42%, #959090 58%, #bdc0bf 75%, #d0d3d2 92%), linear-gradient(180deg, #d5dad9 8%, #ced0cf 25%, #cdcfcd 42%, #b6b7b6 58%, #c4c7c6 75%, #cbcecd 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Packages/29.webp': {
    image:
      'linear-gradient(180deg, #d3dbdd 8%, #ced0d2 25%, #e2e6e9 42%, #dddfe2 58%, #caced1 75%, #e3e5e5 92%), linear-gradient(180deg, #d1d3d6 8%, #d6d7db 25%, #dce4e6 42%, #d8dbda 58%, #ced2d3 75%, #dfe2e3 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Collection/1.webp': {
    image:
      'linear-gradient(180deg, #f8f4e8 8%, #d8d4cb 25%, #ddd5c2 42%, #ded5c1 58%, #e2dc88 75%, #775d45 92%), linear-gradient(180deg, #c995ba 8%, #776e87 25%, #4c4e4d 42%, #3d3f43 58%, #2f3238 75%, #413c39 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Collection/2.webp': {
    image:
      'linear-gradient(180deg, #403b2f 8%, #342426 25%, #2d1825 42%, #402530 58%, #3d242f 75%, #18120f 92%), linear-gradient(180deg, #aba599 8%, #8f7148 25%, #c29357 42%, #584833 58%, #a9a2af 75%, #c7b7b2 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Collection/3.webp': {
    image:
      'linear-gradient(180deg, #cbd1d6 8%, #c2b398 25%, #caba9e 42%, #bcad90 58%, #54524b 75%, #664c2e 92%), linear-gradient(180deg, #ccd5de 8%, #c0b399 25%, #c9ba9c 42%, #ccbda0 58%, #c8ba9c 75%, #baaa8a 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Collection/4.webp': {
    image:
      'linear-gradient(90deg, #908a7b 8%, #b9b19f 25%, #b5b1a0 42%, #69655c 58%, #aea997 75%, #a8a08d 92%), linear-gradient(90deg, #74716b 8%, #6e6c6a 25%, #65615e 42%, #5f5c58 58%, #544f4b 75%, #57554f 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Collection/5.webp': {
    image:
      'linear-gradient(90deg, #836925 8%, #a1957e 25%, #b8af9b 42%, #c3bdb4 58%, #b2aba0 75%, #a49b94 92%), linear-gradient(90deg, #a08531 8%, #c1bba2 25%, #cfcbb7 42%, #d4d1c0 58%, #d2d0c4 75%, #cac9bc 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Collection/6.webp': {
    image:
      'linear-gradient(180deg, #e6d462 8%, #e5d362 25%, #e3d05f 42%, #dfcd5c 58%, #ddcb5a 75%, #dac855 92%), linear-gradient(180deg, #dac65a 8%, #4f5253 25%, #424448 42%, #312a22 58%, #ccb850 75%, #d3c054 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Collection/7.webp': {
    image:
      'linear-gradient(90deg, #030306 8%, #030308 25%, #050308 42%, #090609 58%, #090607 75%, #020204 92%), linear-gradient(90deg, #070507 8%, #0c090c 25%, #0f0a0b 42%, #140e09 58%, #050306 75%, #020204 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Collection/8.webp': {
    image:
      'linear-gradient(90deg, #bca081 8%, #766755 25%, #5d5043 42%, #665949 58%, #637f46 75%, #5f6b41 92%), linear-gradient(90deg, #84a15e 8%, #879f65 25%, #d8cdcb 42%, #718b5b 58%, #aa9b8c 75%, #ac9b8a 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Collection/9.webp': {
    image:
      'linear-gradient(90deg, #aca29c 8%, #8e8981 25%, #726c65 42%, #4c453f 58%, #342e26 75%, #2d2922 92%), linear-gradient(90deg, #cdc9c5 8%, #cdc9c5 25%, #c6c3bf 42%, #b8b3ae 58%, #a59f97 75%, #857e74 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Collection/10.webp': {
    image:
      'linear-gradient(90deg, #ffffff 8%, #ffffff 25%, #8d8889 42%, #847e78 58%, #4b4745 75%, #44403b 92%), linear-gradient(90deg, #8c9096 8%, #8c939c 25%, #858f97 42%, #7c848e 58%, #71757c 75%, #000000 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Collection/11.webp': {
    image:
      'linear-gradient(90deg, #6194c9 8%, #6194c9 25%, #6796ca 42%, #6b9ccb 58%, #73a3cf 75%, #7ea9d3 92%), linear-gradient(90deg, #bab2ac 8%, #b7b1aa 25%, #b6b0a9 42%, #b5afa8 58%, #9e9791 75%, #11161d 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Collection/12.webp': {
    image:
      'linear-gradient(180deg, #fbdfa8 8%, #493723 25%, #24190e 42%, #2d2016 58%, #34251b 75%, #6e5c42 92%), linear-gradient(180deg, #80705d 8%, #7e6143 25%, #765f42 42%, #57442e 58%, #947a5b 75%, #feeaba 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Collection/13.webp': {
    image:
      'linear-gradient(90deg, #b2bcd1 8%, #acb7cd 25%, #8a9cbb 42%, #8296b7 58%, #a9b6ce 75%, #b0bbd1 92%), linear-gradient(90deg, #827e76 8%, #302d29 25%, #cab89b 42%, #aaaa98 58%, #d0bc9d 75%, #816952 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Collection/14.webp': {
    image:
      'linear-gradient(90deg, #0c0707 8%, #0b0606 25%, #0c0605 42%, #8f7153 58%, #6a5337 75%, #120908 92%), linear-gradient(90deg, #0e0606 8%, #0d0605 25%, #0d0605 42%, #0c0605 58%, #0e0705 75%, #100807 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Collection/15.webp': {
    image:
      'linear-gradient(90deg, #100506 8%, #090407 25%, #080307 42%, #080307 58%, #080307 75%, #080307 92%), linear-gradient(90deg, #190f0f 8%, #19100f 25%, #1b1211 42%, #19100f 58%, #180d0d 75%, #170c0b 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Collection/16.webp': {
    image:
      'linear-gradient(90deg, #895233 8%, #89593a 25%, #87532e 42%, #855128 58%, #815128 75%, #805025 92%), linear-gradient(90deg, #322215 8%, #702d23 25%, #392b24 42%, #640f0b 58%, #3c1606 75%, #562008 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Collection/17.webp': {
    image:
      'linear-gradient(180deg, #f9ffff 8%, #ffffff 25%, #879297 42%, #383d45 58%, #222828 75%, #1d1617 92%), linear-gradient(180deg, #5f5d56 8%, #503e3c 25%, #655750 42%, #666764 58%, #12160e 75%, #3b4140 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Collection/18.webp': {
    image:
      'linear-gradient(180deg, #c5b7a6 8%, #c6bcb2 25%, #e9ccac 42%, #141509 58%, #080503 75%, #000002 92%), linear-gradient(180deg, #917859 8%, #8e7454 25%, #8e7454 42%, #9d7d5a 58%, #b18e68 75%, #cba57b 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Vynil/1.webp': {
    image:
      'linear-gradient(180deg, #635641 8%, #af3e3a 25%, #b6423f 42%, #393434 58%, #232122 75%, #4f4a43 92%), linear-gradient(180deg, #47494a 8%, #b14442 25%, #ae4240 42%, #9b2f32 58%, #352c2f 75%, #524b46 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Vynil/2.webp': {
    image:
      'linear-gradient(180deg, #d9645f 8%, #9f3f34 25%, #9c3a2f 42%, #a14238 58%, #a23e32 75%, #46413a 92%), linear-gradient(180deg, #fa8869 8%, #a9473b 25%, #91362d 42%, #9e463c 58%, #9f493e 75%, #47433b 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Napkins/1.webp': {
    image:
      'linear-gradient(180deg, #e5e8f7 8%, #e9edfc 25%, #e9effe 42%, #e9f0fe 58%, #e8effd 75%, #e6ebf9 92%), linear-gradient(180deg, #dbdeed 8%, #e0e3f2 25%, #e2e4f3 42%, #e3e5f5 58%, #e1e4f3 75%, #dee0ef 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Napkins/2.webp': {
    image:
      'linear-gradient(180deg, #e7ecfa 8%, #e9f0fe 25%, #ecf3fe 42%, #edf4ff 58%, #edf4ff 75%, #e9f0fe 92%), linear-gradient(180deg, #e2e8f4 8%, #e6ebf8 25%, #e9eefa 42%, #e9eefa 58%, #e8ecf8 75%, #e4e8f4 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Napkins/3.webp': {
    image:
      'linear-gradient(180deg, #e9edfa 8%, #eaeffb 25%, #eaeffb 42%, #e8edfa 58%, #e8ecf8 75%, #e5e8f5 92%), linear-gradient(180deg, #e7eaf6 8%, #e9eefa 25%, #eaeffb 42%, #eaeffb 58%, #e8ebf9 75%, #e6e8f5 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Napkins/4.webp': {
    image:
      'linear-gradient(90deg, #e6e8f5 8%, #e8ebf8 25%, #eaecfc 42%, #eaecfc 58%, #e8ebf8 75%, #e6e8f5 92%), linear-gradient(90deg, #e6ebf7 8%, #e8eefa 25%, #eaeffb 42%, #e9f1fc 58%, #e9eefa 75%, #e5eaf6 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Napkins/5.webp': {
    image:
      'linear-gradient(180deg, #e9eefa 8%, #e9f0fb 25%, #e9f1fc 42%, #e9f1fc 58%, #e7eefa 75%, #e5ebf6 92%), linear-gradient(180deg, #e6ecf8 8%, #e9effb 25%, #ebf0fc 42%, #ebf0fc 58%, #e9eefa 75%, #e7ecf7 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Napkins/6.webp': {
    image:
      'linear-gradient(180deg, #e8ecf8 8%, #e9eefa 25%, #e9eefa 42%, #e6ebf7 58%, #e4e9f5 75%, #dee4ef 92%), linear-gradient(180deg, #e6eaf6 8%, #e9eefb 25%, #ebf0fc 42%, #ebf0fc 58%, #eaeffb 75%, #e6e8f5 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Napkins/7.webp': {
    image:
      'linear-gradient(180deg, #eaeffb 8%, #ebf1fd 25%, #ebf1fc 42%, #e9effb 58%, #e6ebf7 75%, #e2e7f3 92%), linear-gradient(180deg, #e7ecf8 8%, #eaeffb 25%, #ecf1fd 42%, #ebf0fc 58%, #eaeffb 75%, #e6e9f6 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Napkins/8.webp': {
    image:
      'linear-gradient(180deg, #e6e8f5 8%, #e6ebf7 25%, #e6ebf7 42%, #e7e9f6 58%, #e5e7f4 75%, #e2e5f1 92%), linear-gradient(180deg, #e7edf8 8%, #e9f1fc 25%, #ecf3fe 42%, #ecf3fe 58%, #ebf1fd 75%, #e8effb 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Napkins/9.webp': {
    image:
      'linear-gradient(90deg, #e6e8f5 8%, #e9ecfa 25%, #ebf0fc 42%, #ebf0fc 58%, #eaeffb 75%, #e8ecf8 92%), linear-gradient(90deg, #e6e8f5 8%, #e7ebf7 25%, #e9edfa 42%, #e8ecf8 58%, #e7ebf7 75%, #e5e7f3 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Napkins/10.webp': {
    image:
      'linear-gradient(180deg, #e8ebf7 8%, #ebf0fc 25%, #edf2fe 42%, #edf2fe 58%, #ecf2fd 75%, #e9eefa 92%), linear-gradient(180deg, #e5e7f3 8%, #e7ebf7 25%, #e9ecfa 42%, #e9edfa 58%, #e7eaf7 75%, #e5e7f3 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Napkins/11.webp': {
    image:
      'linear-gradient(180deg, #eaeffb 8%, #ebf2fd 25%, #ecf3fe 42%, #ecf3fe 58%, #ecf3fe 75%, #e8eefa 92%), linear-gradient(180deg, #e8ecf8 8%, #eaf0fb 25%, #ebf0fc 42%, #ebf0fc 58%, #eaeffb 75%, #e7ecf7 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Napkins/12.webp': {
    image:
      'linear-gradient(180deg, #dfe4f0 8%, #e5e7f4 25%, #e6e8f5 42%, #e6e8f5 58%, #e2e7f3 75%, #dce3ed 92%), linear-gradient(180deg, #dce1eb 8%, #e1e5f1 25%, #e3e7f3 42%, #e3e7f3 58%, #e1e5f0 75%, #dbe0ea 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
  'Napkins/13.webp': {
    image:
      'linear-gradient(90deg, #cdcfe0 8%, #d5d7e8 25%, #dbddef 42%, #dee1f2 58%, #dcdff1 75%, #d9daeb 92%), linear-gradient(90deg, #ced2e2 8%, #d4d8e9 25%, #d5d9ea 42%, #d4d9e9 58%, #ccd2e2 75%, #c1c6d5 92%)',
    size: '100% 50%, 100% 50%',
    position: 'center top, center bottom',
  },
  'Napkins/14.webp': {
    image:
      'linear-gradient(180deg, #d0d6e4 8%, #d8dbec 25%, #dae1f1 42%, #dae1f1 58%, #d9e0f0 75%, #d1d8e6 92%), linear-gradient(180deg, #cacddc 8%, #d0d5e4 25%, #d4d8e7 42%, #d5d8e8 58%, #d0d5e4 75%, #caccdb 92%)',
    size: '50% 100%, 50% 100%',
    position: 'left center, right center',
  },
}
